# Generated by Django 4.0.3 on 2022-08-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0007_slidshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=250, verbose_name='Team Name')),
                ('team_details', models.TextField(verbose_name='Team Detail')),
                ('team_Img', models.ImageField(null=True, upload_to='Team_images/', verbose_name='Team Photo')),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='Date')),
                ('team_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t', to='serviceApp.category', verbose_name='Team Category')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
