# Generated by Django 4.0.3 on 2022-08-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0009_alter_team_team_details_alter_team_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_cat',
        ),
    ]
