# Generated by Django 4.0.3 on 2022-08-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0010_remove_team_team_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_Img',
            field=models.ImageField(null=True, upload_to='Team_images/', verbose_name='Photo'),
        ),
    ]
