# Generated by Django 4.0.3 on 2022-08-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0011_alter_team_team_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='date',
        ),
        migrations.AlterField(
            model_name='team',
            name='team_Img',
            field=models.ImageField(null=True, upload_to='team_imag/', verbose_name='Team Photo'),
        ),
    ]
