# Generated by Django 4.0.3 on 2022-08-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0012_remove_team_date_alter_team_team_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_Img',
            field=models.ImageField(null=True, upload_to='team_image/', verbose_name='Team Photo'),
        ),
    ]
