# Generated by Django 4.0.3 on 2022-08-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0013_alter_team_team_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_Img',
            new_name='team_img',
        ),
    ]
